#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'chef-client'
cookbook 'redis'
cookbook 'python'
cookbook 'nvm'
cookbook 'git'
cookbook 'rabbitmq'
cookbook 'nginx'
cookbook 'geos'
cookbook 'gdal',
  :git => 'https://github.com/rootart/gdal-chef'

cookbook 'proj'

cookbook 'postgresql',
  :git => 'https://github.com/phlipper/chef-postgresql'

cookbook 'rvm',
  :git => 'git://github.com/fnichol/chef-rvm.git', :ref => 'v0.9.0'
