#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'chef-client'
cookbook 'redis'
cookbook 'python'
cookbook 'nvm'
cookbook 'git'
cookbook 'rabbitmq'
cookbook 'nginx'
cookbook 'rvm',
  :git => 'https://github.com/fnichol/chef-rvm'

cookbook 'postgresql',
  :git => 'https://github.com/phlipper/chef-postgresql'
